### ISSUE TITLE
"Demo" tests should include at least 1 or more Flaky tests

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/java-demo-app#10]
![image](https://user-images.githubusercontent.com/3640206/77949155-7f9ddd80-7294-11ea-9c50-c6db62faeb3c.png)

**Comment by borjaburgos** [comment]
Change that to `demotest` to be consistent with other projects.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78014454-3e670580-7348-11ea-9d06-6f4805a16018.png)
