### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/java-demo-app#11]
README should contain instructions on how to clone this project and how to run it locally with Scope for Mac/Windows to obtain Scratchpad results. 

Ideally, all integration tests are automatically configured to be ran against our "production" hamburguesía instance, such that when I run them locally I still the full traces in Scratchpad. 

Except this service doesn't do any integration tests... if that's the case, where no tests run agains "production" hamburguesía, then have instructions on how to spin up the necessary dependencies (databases, etc.) using a dockercompose file or similar.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78014346-18416580-7348-11ea-927b-254d3ad3855b.png)
