### ISSUE TITLE
Increase test to improve fill out TEST DURATION HISTOGRAM

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/java-demo-app#12]
Add an identifier to "dummy" tests. As such, this project would have:

- a very limited amount of "demotest" tests (1-5)
- a lot of "dummy" tests (~1000s)
- any other test that may not be dummy tests, but still not interesting enough to be highlighted as "demo"

Since "benchmark" tests can easily be filtered in the UI, there's no need to append a qualifier to these tests, unless there's any one benchmark test that is particularly interesting.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78014563-65bdd280-7348-11ea-9547-de5fcbab7de5.png)
