### ISSUE TITLE
Open PRs from feature branches to populate `PR` tab in Explore view

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/java-demo-app#7]
![image](https://user-images.githubusercontent.com/3640206/77948773-e8d12100-7293-11ea-9e42-cd8fbe3a388e.png)

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/77998122-d8bb4f00-7330-11ea-9a0d-92b4069a3acd.png)
