### ISSUE TITLE
Every test tagged as "demotest" should have at least 1 or more executions. 

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/java-demo-app#9]
![image](https://user-images.githubusercontent.com/3640206/77949067-58dfa700-7294-11ea-9581-f41e5bcd6a8f.png)

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78014097-b97bec00-7347-11ea-9771-3b956f2b1ef8.png)
